# Generated by Django 4.0.5 on 2022-06-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=500, verbose_name='Город')),
                ('okato', models.IntegerField(verbose_name='ОКАТО')),
                ('population', models.IntegerField(verbose_name='Населения')),
                ('founded_in', models.IntegerField(verbose_name='Основание')),
                ('status_of_city', models.IntegerField(verbose_name='Статус города')),
            ],
            options={
                'verbose_name': 'Городские населённые пункты Московской области',
                'verbose_name_plural': 'Городские населённые пункты Московской области',
            },
        ),
    ]
