# Generated by Django 4.0.5 on 2022-06-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityinfo',
            name='id_from_page',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
