# Generated by Django 4.0.5 on 2022-06-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_cityinfo_id_from_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='id_from_page',
            field=models.IntegerField(unique=True),
        ),
    ]
