# Generated by Django 4.0.5 on 2022-07-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_cityinfo_id_from_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='population',
            field=models.BigIntegerField(verbose_name='Населения'),
        ),
    ]
